language: go

go:
   - 1.6

install:
- export PATH=$PATH:$HOME/gopath/bin
- go get github.com/golang/mock/gomock
- go get github.com/lcaballero/exam
- cd $HOME/gopath/src/github.com/golang/mock/gomock

script: go test --race ./...