* Introduction
** Overview
~exam~ is a small set of convenience functions designed to help
examine and assert values when writing test cases.
** Installation

#+BEGIN_SRC shell
go get github.com/lcaballero/exam
#+END_SRC

** Usage

*** IsZero(t, actual, expected)

#+BEGIN_SRC go
n := 0
IsZero(t, n)
#+END_SRC


*** IsEqInt(t, actual, expected)

#+BEGIN_SRC go
n := 1
IsEqInt(t, n, 1)
#+END_SRC

*** GreaterThan(t, actual, expected)

#+BEGIN_SRC go
n := 2
GreaterThan(t, n, 1)
#+END_SRC

*** IsTrue(t, actual)

#+BEGIN_SRC go
n := 3
IsTrue(t, n == 3)
#+END_SRC

*** IsFalse(t, actual)

#+BEGIN_SRC go
n := 4
IsFalse(t, n == 3)
#+END_SRC

*** IsEqBytes(t, actual)

#+BEGIN_SRC go
a := []byte{ 'a', 'b', 'c' }
b := []byte("abc")
IsEqBytes(t, a, b)
#+END_SRC

*** IsEqByte(t, actual)

#+BEGIN_SRC go
a := []byte{ 'a', 'b', 'c' }
b := []byte("abc")
IsEqByte(t, a[1], b[1])
#+END_SRC

*** IsNotNil(t, actual)

#+BEGIN_SRC go
type mystruct struct {}
my := &mystruct{}
IsNotNil(t, my)
#+END_SRC

*** IsNil(t, actual)

#+BEGIN_SRC go
var my *mystruct
IsNil(t, my)
#+END_SRC

*** ShouldPanic(t, fn)

#+BEGIN_SRC go
willPanic := func() {
    panic("panicking... now...")
}
ShouldPanic(t, willPanic)
#+END_SRC

*** ShouldNotPanic(t, fn)

#+BEGIN_SRC go
dontPanic := func() {
    // panicking... now...
}
ShouldNotPanic(t, dontPanic)
#+END_SRC

** License

*** See license file.

The use and distribution terms for this software are covered by the
[[http://opensource.org/licenses/eclipse-1.0.txt][EPL-1]], which can be found in the file 'license' at the
root of this distribution. By using this software in any fashion, you are
agreeing to be bound by the terms of this license. You must not remove this
notice, or any other, from this software.


